const styles = {
  container: { minHeight: '100vh', background: '#f5f5f5' },
  header: { background: '#667eea', color: 'white', padding: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  logo: { margin: 0, fontSize: '24px' },
  userInfo: { display: 'flex', gap: '15px', alignItems: 'center' },
  logoutBtn: { background: 'white', color: '#667eea', border: 'none', padding: '8px 16px', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' },
  tabs: { display: 'flex', gap: '10px', padding: '0 20px', borderBottom: '2px solid #ddd' },
  tab: { background: 'none', border: 'none', padding: '15px 20px', cursor: 'pointer', fontSize: '16px', color: '#666' },
  activeTab: { background: 'none', border: 'none', padding: '15px 20px', cursor: 'pointer', fontSize: '16px', color: '#667eea', borderBottom: '3px solid #667eea' },
  content: { padding: '20px' },
  jobsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '20px', marginTop: '20px' },
  jobCard: { background: 'white', padding: '20px', borderRadius: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' },
  department: { color: '#666', fontSize: '14px' },
  badge: { padding: '5px 10px', borderRadius: '5px', color: 'white', fontSize: '12px', fontWeight: 'bold' },
  jobMeta: { marginTop: '15px', marginBottom: '15px' },
  applyBtn: { width: '100%', padding: '10px', background: '#667eea', color: 'white', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' },
  applicationsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(400px, 1fr))', gap: '20px', marginTop: '20px' },
  appCard: { background: 'white', padding: '20px', borderRadius: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' },
  editSection: { marginTop: '10px' },
  editBox: { display: 'flex', flexDirection: 'column', gap: '10px' },
  select: { padding: '8px', borderRadius: '5px', border: '1px solid #ddd' },
  editButtons: { display: 'flex', gap: '10px' },
  saveBtn: { flex: 1, padding: '10px', background: '#667eea', color: 'white', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' },
  cancelBtn: { flex: 1, padding: '10px', background: '#ddd', color: '#333', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', padding: '20px' },
  statCard: { background: 'white', padding: '20px', borderRadius: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' },
  statNumber: { fontSize: '32px', fontWeight: 'bold', color: '#667eea', margin: '10px 0' },
  status: { display: 'inline-block', padding: '5px 15px', borderRadius: '20px', color: 'white', fontWeight: 'bold', marginTop: '10px' },
  timeline: { marginTop: '20px', padding: '15px', background: '#f9f9f9', borderRadius: '5px' },
  timelineItem: { marginBottom: '15px', paddingBottom: '15px', borderBottom: '1px solid #ddd' },
  comment: { marginTop: '5px', fontStyle: 'italic', color: '#666' },
  modal: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  modalContent: { background: 'white', padding: '30px', borderRadius: '10px', width: '90%', maxWidth: '500px' },
  input: { width: '100%', padding: '10px', marginBottom: '15px', border: '1px solid #ddd', borderRadius: '5px', fontSize: '16px' },
  modalButtons: { display: 'flex', gap: '10px' },
  submitBtn: { flex: 1, padding: '10px', background: '#667eea', color: 'white', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' }
};

export default styles;
